djangonautic/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
	
	path('signup/', views.signup_view, name='signup'),  # name = 'signup' => namespacing the url so that it can be used later on
	path('login/', views.login_view, name='login'),
	path('logout/', views.logout_view, name='logout'),

]

djangonautic/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name='list'),
    path('create/', views.article_create, name='create'),
    path('<slug:slug>/', views.article_detail, name='detail'),
]

djangonautic/djangonautic/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('about/', views.about),
    path('', article_views.article_list, name="home"),
]

urlpatterns += staticfiles_urlpatterns()   # ask django to serve the static files 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangonautic/accounts/models.py
from django.db import models

# Create your models here.

djangonautic/articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
	#attributes = fields
	title = models.CharField(max_length=100)
	slug = models.SlugField(unique=True)
	body = models.TextField()
	date = models.DateTimeField(auto_now_add=True)
	thumb = models.ImageField(default="default.png", blank=True)
	author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
	#add in a author

	def __str__(self):
		return self.title

	def snippet(self):
		return self.body[:50] + '...'

# python manage.py makemigrations
# python manage.py migrate


 

djangonautic/articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
	class Meta:
		model = models.Article
		fields = ['title', 'body', 'slug', 'thumb']

djangonautic/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
# Create your views here.

def signup_view(req):
	if req.method == 'POST':
		form = UserCreationForm(req.POST)
		if form.is_valid():
			user = form.save()
			# log the user in
			login(req, user)
			return redirect('articles:list')
	else:
		form = UserCreationForm()
		
	return render(req, 'accounts/signup.html', {'form': form})


def login_view(req):
	if req.method == 'POST':
		form = AuthenticationForm(data=req.POST)
		if form.is_valid():
			# login the user
			user = form.get_user()
			login(req, user)
			if 'next' in req.POST:
				return redirect(req.POST.get('next'))
			else:
				return redirect('articles:list') # using url namespaced in articles so if I just specify x it will redirect to /accounts/x

	else:
		form = AuthenticationForm()

	# req.GET.get('next') is used to get the next part of query string 
	return render(req, 'accounts/login.html', {'form': form, 'nxt': req.GET.get('next')})


def logout_view(req):
	if req.method == 'POST':
		logout(req)
		return redirect('articles:list')
 

djangonautic/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.
def article_list(req):
	articles = Article.objects.all().order_by('date')
	return render(req, 'articles/article_list.html', {'articles':articles})

def article_detail(req, slug):
	#return HttpResponse(slug)
	article = Article.objects.get(slug=slug)
	return render(req, 'articles/article_detail.html', {'article': article})


@login_required(login_url="/accounts/login")    # even "accounts:login" would have worked
def article_create(req):
	if req.method == 'POST':
		form = forms.CreateArticle(req.POST, req.FILES)
		if form.is_valid():
			# save article to db
			instance = form.save(commit=False)
			instance.author = req.user
			instance.save()
			return redirect('articles:list')
	else:
		form = forms.CreateArticle()
	return render(req, 'articles/article_create.html', {'form': form})

djangonautic/djangonautic/views.py
#Contains set of all callback functions to execute

from django.http import HttpResponse
from django.shortcuts import render


def homePage(req):
	#return HttpResponse('home page')
	return render(req, 'homepage.html')

def about(req):
	#return HttpResponse('about')
	return render(req, 'about.html')

djangonautic/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Login</h1>
<form class="site-form" action="{% url 'accounts:login' %}" method="post">
  {% csrf_token %}
  {{form}}
  {% if nxt %}
  	<input type="hidden" name="next" value="{{ nxt }}">
  {% endif %}
  <input type='submit' value='Login'>
</form>

{% endblock %}

djangonautic/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Signup</h1>
<form class="site-form" action="/accounts/signup/" method="post">
  {% csrf_token %}
  {{form}}
  <input type='submit' value='Signup'>
</form>

{% endblock %}

djangonautic/articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}

  <div class='create_article'>
  	<h2>Create an awesome new article</h2>
  	<form class='site-form' action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
  		{% csrf_token %}
  		{{form}}
  		<input type="submit" value="Create">
  	</form>
  </div>
  <script src="/static/slugify.js"></script>

{% endblock %}

djangonautic/articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}

<div class='article-detail'>
  <div class='article'>
  	<img src="{{article.thumb.url}}"/>
  	<h2>{{article.title}}</h2>
  	<p>{{article.body}}</p>
  	<p>{{article.date}}</p>
  </div>
</div>


{% endblock %}

djangonautic/articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}
{% block content %}	
  <h1>Articles</h1>
  <div class='articles'>
	  {%for article in articles%}
	  	<div class='article'>
	  	  <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h2>
	  	  <p>{{article.snippet}}</p>
	  	  <p>{{article.date}}</p>
	  	  <p class="author">added by {{article.author.username}}</p>
	  	</div>
	  {%endfor%}
	</div>
{% endblock %}
  

djangonautic/templates/about.html
<!DOCTYPE html>
<html>
  <head>
  	<meta charset='utf-8'>
  </head>
  <body>
  	<h1>About Us</h1>
  	<p>Call us</p>
  </body>
</html

djangonautic/templates/base_layout.html
{%load static from staticfiles%}
<!DOCTYPE html>
<html>
  <head>
  	<meta charset='utf-8'>
  	<link rel="stylesheet" href="{%static 'style.css'%}">
  </head>
  <body>
    <header class="wrapper">
    <h1><a href="{% url 'home' %}"><img src="{% static 'logo.png' %}"/></a></h1>
      <nav>
        <ul>
          {% if user.is_authenticated %}
          <li>
            <form class="logout-link" action="{% url 'accounts:logout' %}" method='post'>
              {% csrf_token %}
              <button type="submit">Logout</button>
            </form>
          </li>
          <li><a href="{% url 'articles:create' %}" class="highlight">New Article</a></li>
          {% else %}
          <li>
            <a href="{% url 'accounts:login' %}">Login</a>
          </li>
          <li>
            <a href="{% url 'accounts:signup' %}">Signup</a>
          </li>
          {% endif %}
        </ul>
      </nav>
    </header>
  	<div class='wrapper'>
  	  {% block content %}
  	  {% endblock %}
  	</div> 
  </body>
</html

djangonautic/templates/homepage.html
<!DOCTYPE html>
<html>
  <head>
  	<meta charset='utf-8'>
  </head>
  <body>
  	<h1>This is the homepage</h1>
  	<p>Welcome to djangonautic</p>
  </body>
</html